export type GameSong = {
  id: string;
  title: string;
};

export const spotifyPlaylistUrl =
  "https://open.spotify.com/playlist/6N2p3X3BzAGlBn3SQCfAGB";

export const gameSongs: GameSong[] = [
  { id: "0Jirkb7LGNWyVhKOsKFdZ2", title: "Run Away With Me" },
  { id: "5ucGbZG1Eg3358FICjMVur", title: "Emotion" },
  { id: "6ss2vUwrV64xAVE4fXZMIh", title: "I Really Like You" },
  { id: "4V2qQZUW2Hcs4zFKjKafs2", title: "Gimmie Love" },
  { id: "4PijdRV622NbKXowFC5tdS", title: "All That" },
  { id: "6EZLcNpHEMWjVm7tfU90em", title: "Boy Problems" },
  { id: "2J8jaVl5KkWW9wVa7CC3Gi", title: "Making The Most Of The Night" },
  { id: "5DerNWKZt27S4dD6jjgg92", title: "Your Type" },
  { id: "7mc4liEp2BJl9yj5qYUMdc", title: "Let's Get Lost" },
  { id: "7DY2hdo5qsl2400Wu8ZGnO", title: "LA Hallucinations" },
  { id: "2udKAiJYivJI12mrUGGDpA", title: "Warm Blood" },
  { id: "5gwDxtCoBbc6nE8IePV9yq", title: "When I Needed You" },
  { id: "0Fx3fYbcYx3iDNrduNMlde", title: "Surrender My Heart" },
  { id: "6432lWvaitYvc6a96eENKX", title: "Joshua Tree" },
  { id: "7I7Dk8FOkZqhqZp9N2RKiP", title: "Talking to Yourself" },
  { id: "0AJHV1mzwpQHmgej8FakhH", title: "Far Away" },
  { id: "1oarZ29ZGSZwJa8o30lV46", title: "Sideways" },
  { id: "3v61sG0y5M1LnSsFN4IimM", title: "Beach House" },
  { id: "2nwgjU7khPnusiP4keln0s", title: "Bends" },
  { id: "374EKgkkuCrw0ovQPYn1vT", title: "Western Wind" },
  { id: "6NvUdePT7c3G25xzJHT1cC", title: "So Nice" },
  { id: "73FThBFlbAINUou2L7mdfR", title: "Bad Thing Twice" },
  { id: "3nbDQdyujeg7dTTSZxVXWO", title: "Shooting Star" },
  { id: "0nrKz8Ez1mQ1wiv1oqc7Ld", title: "Go Find Yourself or Whatever" },
  { id: "6c6vULMrRuN4NECs2iB1xe", title: "The Loneliest Time (feat. Rufus Wainwright)" },
  { id: "1dTkx1nSrcMSUoGffsn07A", title: "Anxious - Bonus Track" },
  { id: "6AGklQLROYjvD8qxAPrk3b", title: "No Thinking Over the Weekend - Bonus Track" },
  { id: "1gp2oWZSi4ucFCvJU763Uq", title: "Keep Away - Bonus Track" },
  { id: "6DUzRqe6EohKknMQNaqgCU", title: "Anything to Be With You" },
  { id: "6hdVsxujJNEsIbTNHvbVvK", title: "Kamikaze" },
  { id: "3VTBdEPBlb52WqO3200N84", title: "After Last Night" },
  { id: "14zKFFFOEHbCBahh9wWFsJ", title: "Aeroplanes" },
  { id: "2diHObxEyYlftJ2pPIB3eG", title: "Shy Boy" },
  { id: "6vX00oaG3bMuNBKxapoPYO", title: "Kollage" },
  { id: "6vJSLX1aqt8mVFK2j5Lk6C", title: "Shadow" },
  { id: "7zy2kNoeD72x2NEDaAsJOX", title: "Psychedelic Switch" },
  { id: "1SX0ymMOeU0JpYdTfiGTIS", title: "So Right" },
  { id: "6JC9VO8xffWNFGzucmNnmB", title: "Come Over" },
  { id: "33gK7HoPnsoaBKTEOBFg1X", title: "Put It To Rest" },
  { id: "6iz2UvoC09YTRZZOixdRJw", title: "Stadium Love" },
  { id: "6h9IrMchXOKBKqb1loNQWB", title: "Weekend Love" },
  { id: "5ovKXoPXsaCydETxiqbt80", title: "Julien" },
  { id: "2YTblAt3gfs9F3DGYIv2nK", title: "No Drug Like Me" },
  { id: "3dtp75StyEK5XeKraS5KiI", title: "Now That I Found You" },
  { id: "6cDPJqKw8PUBw5SigKszrL", title: "Want You In My Room" },
  { id: "6wFpWuVxpcYWXw7xzj0Wpt", title: "Everything He Needs" },
  { id: "4hDBBUfxZom9yCl67A8UAe", title: "Happy Not Knowing" },
  { id: "51UAm8F9u16skm1R1ckMwr", title: "I'll Be Your Girl" },
  { id: "7kG3DPhoPsltuT0vxENI6E", title: "Too Much" },
  { id: "2ZdEU0Ys9frp2y0Z950jWR", title: "The Sound" },
  { id: "69XN0XjxcMtUCrvOEd0KYd", title: "Automatically In Love" },
  { id: "11gPrIAQGSmQhngUpb0XC2", title: "Feels Right" },
  { id: "0pn8Vl8oFmIp0r21Zwpb76", title: "Right Words Wrong Time" },
  { id: "70SnF1RJLB3blEDBWjrig3", title: "Real Love" },
  { id: "7CmsSwmE781TU53esN7BK0", title: "For Sure" },
  { id: "7KW3XQV5Or5CF57MYVj5h4", title: "Party For One" },
  { id: "03o4HPzUwftpgAPNQSuaBS", title: "This Love Isn't Crazy" },
  { id: "1oRUYnECbObJ6iQip1qvZR", title: "Window" },
  { id: "6gynJ5Th3rGXAt1IHBAiU3", title: "Felt This Way" },
  { id: "0z7Cp31iutNj2Gp8o85cbI", title: "Stay Away" },
  { id: "15Dsy8ojgto8ie8kTfTmQn", title: "This Is What They Say" },
  { id: "3Llw7oR2GBjgZwSNtWfqlL", title: "Heartbeat" },
  { id: "3UK2G7CRI6aYnJyI0Aedl7", title: "Summer Love" },
  { id: "29kq7sv74FL5MiJB8v1ZbZ", title: "Fake Mona Lisa" },
  { id: "7kynjj6npqbbW8xiVRAqku", title: "Let's Sort The Whole Thing Out" },
  { id: "4KKAVfbXHsBbU6j11TJ29O", title: "Comeback" },
  { id: "17gMpE86ah5hy6i5MOGEdN", title: "Solo" },
  { id: "04mnVzyNtoKBig5g3X64rk", title: "Now I Don't Hate California After All" },
  { id: "1mQpK73Pm5cc9Kg3Qm4RtE", title: "First Time" },
  { id: "3MXDEDLmQPSQvoyJIYbIp3", title: "Higher" },
  { id: "3Lnb561DlckyyTSONuqbLQ", title: "The One" },
  { id: "3pIYV8ajPqkgTABRR54rWP", title: "Fever" },
  { id: "3l4eYYvCzqd2Q37KkOBZGC", title: "Body Language" },
  { id: "7wgxq27uOvfydLunYkcmAU", title: "Cry" },
  { id: "0h5cHAx4g0l3ppyxK6OYtd", title: "Store" },
  { id: "21WYgbVZkF0lKwi7Nlsgjf", title: "Roses" },
  { id: "29KCgoJwNofk7hF4Z1wsEB", title: "On Wires" },
  { id: "3DzSzffpw57NZtx2wDyQCA", title: "Favourite Colour" },
  { id: "7ahWow6nyGdUdsXJYYzyjK", title: "I Didn't Just Come Here To Dance" },
  { id: "6uyal2czBILfPJOm2dLSJM", title: "Black Heart" },
  { id: "2CG3lX8ddjTEQL4kwBHkw3", title: "Don't Leave Me on the Dance Floor" },
  { id: "1C3SJEsAIPrHNz6bNZepoQ", title: "After All" },
  { id: "59edZBlolguuivWORanXkJ", title: "Motivation" },
  { id: "5SenloD1HJ0w5HV70TTLAK", title: "Ordinary Superstar" },
];
